### ISSUE TITLE
Constructor should check / enforce the invariant

### ISSUE THREAD

**Issue by cbeck88** [Aszarsha/zstring_view#1]
```
basic_zstring_view( CharT const * s, size_type sz ): string_view_base{ s, sz } {   }
```

I think there should be some check for the null-terminator, do you agree?

```
basic_zstring_view( CharT const * s, size_type sz ): string_view_base{ s, sz } {  assert('\0' == s[sz] && "zstring_view contract was violated, no null character was found"); }
```

**Comment by Aszarsha** [comment]
Thank you very much for your suggestion ! It is greatly appreciated.

In general, I think that 1) it's the user's responsibility to ensure correct use of an interface (here that the parameter represent a null-terminated string), and that 2) plain and obvious errors and behaviors are much better that three-quarter-of-the-time catches that overshadow potential bugs.

This specific assert would probably provide a very false sense of security. Indeed, if the parameters do not represent a null-terminated string, they probably are not a string at all and who knows what s and sz actually are. Dereferencing s+sz might then indeed result in a '\0' character (from a memory mapped file, for example, which is quite common in this context !) leading to difficult debug sessions (thinking that we're safe through the assert) : zstring_view constructed ; not actually a zstring... Ouch.

Overall, it certainly depends on the project policy. If this code is to be used in a project with many different programmers and that is using a heavily partitioned black-boxes structure, then maybe ensuring correct use as much as possible (which really is *never* enough) could be desirable. 
Certainly, feel free to add as many checks as you deem necessary in your situation.
